Inline TemporaryAccountLogger::LOG_TYPE
Testing that an extension is disabled with usage of a class of that extension fails, when the extension is really not installed.
1) MediaWiki\Extension\AbuseFilter\Tests\Integration\ProtectedVarsAccessLoggerTest::testLogs_CUDisabled with data set "enable access to protected vars values" (array('logAccessEnabled', array()), array('af-change-access-enable', 'change-access-enable'))
Error: Class "MediaWiki\CheckUser\Logging\TemporaryAccountLogger" not found

Since 1e5edabf74 / I363401711f test is no longer in master

Change-Id: Id3ae8557f3bcd7db466e77c450e5b73690b750ba