selenium: Await isDisplayed assert in async test
It is not needed to await ViewListPage.filterSavedNotice, but
isDisplayed().

After test timeout the test hangs until build timeout:
Error in "When importing a filter.Data on the editing interface is
correct.the imported data can be saved"
Error: Timeout of 60000ms exceeded. The execution in the test "Data on
the editing interface is correct the imported data can be saved" took
too long. Try to reduce the run time or increase your timeout for test
specs (https://webdriver.io/docs/timeouts).
(/workspace/src/extensions/AbuseFilter/tests/selenium/specs/importingFilters.js)

Bug: T389536
Change-Id: Ia0cce4c5c1728181c02ce573811608b9372f1f89